import { Question } from './types';

export const quizRegistry: Record<string, () => Promise<{ [key: string]: Question[] }>> = {
  // Physics
  'phy-measurements': () => import('./data/physicsMeasurementsQuestions'),
  'phy-vectors': () => import('./data/physicsVectorsQuestions'),
  'force-motion': () => import('./data/physicsForceMotionQuestions'),
  'work': () => import('./data/physicsWorkEnergyQuestions'),
  'p-circular': () => import('./data/physicsCircularQuestions'),
  'fluid-dynamics': () => import('./data/physicsFluidQuestions'),
  'oscillations': () => import('./data/physicsOscillationQuestions'),
  'waves': () => import('./data/wavesQuestions'),
  'physical-optics': () => import('./data/physicsOpticsQuestions'),
  'optical-instruments': () => import('./data/physicsInstrumentQuestions'),
  'thermodynamics': () => import('./data/physicsThermodynamicsQuestions'),
  'p-electrostatics': () => import('./data/physicsElectrostaticsQuestions'),
  'current-electricity': () => import('./data/physicsElectricityQuestions'),
  'electromagnetism': () => import('./data/physicsElectromagnetismQuestions'),
  'electromagnetic-induction': () => import('./data/physicsInductionQuestions'),
  'alternating-current': () => import('./data/physicsACQuestions'),
  'physics-of-solids': () => import('./data/physicsSolidQuestions'),
  'electronics': () => import('./data/electronicsQuestions'),
  'modern-physics': () => import('./data/modernPhysicsQuestions'),
  'atomic-spectra': () => import('./data/atomicSpectraQuestions'),
  'nuclear-physics': () => import('./data/nuclearPhysicsQuestions'),

  // Biology
  'bio-intro': () => import('./data/biologyIntroQuestions'),
  'bio-molecules': () => import('./data/biologyMoleculesQuestions'),
  'bio-enzymes': () => import('./data/biologyEnzymesQuestions'),
  'bio-cell': () => import('./data/biologyCellQuestions'),
  'bio-variety-life': () => import('./data/biologyVarietyLifeQuestions'),
  'bio-prokaryotes': () => import('./data/biologyProkaryotesQuestions'),
  'bio-protists': () => import('./data/biologyProtistsFungiQuestions'),
  'bio-fungi': () => import('./data/biologyProtistsFungiQuestions'),
  'bio-plantae': () => import('./data/biologyPlantaeQuestions'),
  'bio-animalia': () => import('./data/biologyAnimaliaQuestions'),
  'bio-bioenergetics': () => import('./data/biologyBioenergeticsQuestions'),
  'bio-nutrition': () => import('./data/biologyNutritionQuestions'),
  'bio-exchange': () => import('./data/biologyExchangeQuestions'),
  'bio-transport': () => import('./data/biologyTransportQuestions'),
  'bio-homeostasis': () => import('./data/biologyHomeostasisQuestions'),
  'bio-support': () => import('./data/biologySupportMovementQuestions'),
  'bio-coordination': () => import('./data/biologyCoordinationQuestions'),
  'bio-reproduction': () => import('./data/biologyReproductionQuestions'),
  'bio-growth': () => import('./data/biologyGrowthQuestions'),
  'bio-dna': () => import('./data/biologyDNAQuestions'),
  'bio-cell-cycle': () => import('./data/biologyCellCycleQuestions'),
  'bio-genetics': () => import('./data/biologyGeneticsQuestions'),
  'bio-biotech': () => import('./data/biologyBiotechQuestions'),
  'bio-evolution': () => import('./data/biologyEvolutionQuestions'),
  'bio-ecosystem': () => import('./data/biologyEcosystemQuestions'),
  'bio-major-eco': () => import('./data/biologyMajorEcosystemQuestions'),
  'bio-environment': () => import('./data/biologyEnvironmentQuestions'),

  // Chemistry
  'ch-basic-concepts': () => import('./data/chemistryBasicConceptsQuestions'),
  'ch-experimental-tech': () => import('./data/chemistryExperimentalTechQuestions'),
  'ch-gases': () => import('./data/chemistryGasesQuestions'),
  'ch-liquids-solids': () => import('./data/chemistryLiquidsSolidsQuestions'),
  'ch-atomic-structure': () => import('./data/chemistryAtomicStructureQuestions'),
  'ch-chemical-bonding': () => import('./data/chemistryBondingQuestions'),
  'ch-thermochemistry': () => import('./data/chemistryThermochemistryQuestions'),
  'chem-equilibrium': () => import('./data/chemistryEquilibriumQuestions'),
  'ch-solutions': () => import('./data/chemistrySolutionsQuestions'),
  'ch-electrochemistry': () => import('./data/chemistryElectrochemistryQuestions'),
  'ch-kinetics': () => import('./data/chemistryKineticsQuestions'),
  'ch-periodic-class': () => import('./data/chemistryPeriodicQuestions'),
  'ch-s-block': () => import('./data/chemistrySBlockQuestions'),
  'ch-group-3a-4a': () => import('./data/chemistryGroup34Questions'),
  'ch-group-5a-6a': () => import('./data/chemistryGroup56Questions'),
  'ch-halogens-noble': () => import('./data/chemistryHalogenQuestions'),
  'ch-transition-elements': () => import('./data/chemistryTransitionQuestions'),
  'ch-organic-principles': () => import('./data/chemistryOrganicIntroQuestions'),
  'ch-aliphatic-hydrocarbons': () => import('./data/chemistryAliphaticQuestions'),
  'ch-aromatic-hydrocarbons': () => import('./data/chemistryAromaticQuestions'),
  'ch-alkyl-halides': () => import('./data/chemistryAlkylHalideQuestions'),
  'ch-alcohols-phenols': () => import('./data/chemistryAlcoholQuestions'),
  'ch-aldehydes-ketones': () => import('./data/chemistryCarbonylQuestions'),
  'ch-carboxylic-acids': () => import('./data/chemistryAcidQuestions'),
  'ch-macromolecules': () => import('./data/chemistryMacromoleculeQuestions'),
  'ch-industries': () => import('./data/chemistryIndustryQuestions'),
  'ch-environmental': () => import('./data/chemistryEnvironmentQuestions'),

  // Logical Reasoning
  'lr-critical': () => import('./data/logicalCriticalQuestions'),
  'lr-series': () => import('./data/logicalSeriesQuestions'),
  'lr-symbol': () => import('./data/logicalSymbolQuestions'),
  'lr-deductions': () => import('./data/logicalDeductionQuestions'),
  'lr-problems': () => import('./data/logicalProblemQuestions'),
  'lr-action': () => import('./data/logicalActionQuestions'),
  'lr-cause-effect': () => import('./data/logicalCauseQuestions'),
};
